version: '3.3'

services:
  postgres:
    image: chucknorrisio/postgres
    container_name: chucknorris-postgres
    ports:
      - "5432:5432"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: chucknorris-swagger
    ports:
      - "4567:8080"
    environment:
      API_URL: "http://localhost:8080/documentation"
