name: Build

on:
  workflow_call:
    inputs:
      version:
        description: Version to build
        required: true
        type: string

env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: 21

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          ref: ${{ inputs.version }}
      - run: ./gradlew test