name: Build

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

jobs:

  verification:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'
      - run: |
          ./gradlew test