name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.sha }}

  deploy:
    needs: build
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ github.sha }}
